version: "3.9"
services:
  cvtcaptcha:
    container_name: cvtcaptcha
    build:
      context: .
      dockerfile: Dockerfile2
      args:
        APP_VERSION: ${APP_VERSION}
    image: cvtcaptcha:${APP_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - logs:/app/logs
    networks:
      - cvtcaptcha-network
    restart: unless-stopped

  db:
    image: postgres:17
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cvtcaptcha-network
    restart: unless-stopped

volumes:
  db_data:
  logs:

networks:
  cvtcaptcha-network: