spring:
  application:
    name: cvtcaptcha
    version: ${project.version}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-ms: 3600000
  devtools:
    restart:
      enabled: false

server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

com:
  tomcvt:
    request:
      anon-rate-limit:
        max-requests: 500
        time-window-ms: 600000 # 10 minutes
        ban-rate-per-minute: 120
        ban-duration-ms: 7200000 # 2 hours
      default-user-limit:
        hourly-max-requests: 60000
        daily-max-requests: 600000
      ip-registry-cleaner:
        interval-ms: 3600000 # 1 hour
    captcha:
      anon-rate-limit:
        max-requests: 20
        time-window-ms: 3600000
      default-user-limit:
        hourly-max-requests: 1000
        daily-max-requests: 10000
      expiration-ms: 300000 # 5 minutes
      max-attempts: 3
    cvt-token:
      secret: ${CVT_TOKEN_SECRET}
      expiration-ms: 600000 # 10 minutes
    hmac-hash-service:
      secret: ${API_KEY_GENERATOR_SECRET}
    superuser:
      username: ${SUPERUSER_USERNAME}
      password: ${SUPERUSER_PASSWORD}
      api-key: ${SUPERUSER_API_KEY}
    url-origin: ${URL_ORIGIN}

app:
  domain: ${URL_ORIGIN}
  captcha-dir: storage
  image:
    width: 400
    height: 300
    emote-r: 36