spring:
  application:
    name: cvtcaptcha
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-ms: 3600000

com:
  tomcvt:
    request:
      anon-rate-limit:
        max-requests: 100
        time-window-ms: 60000
      default-user-limit:
        hourly-max-requests: 60000
        daily-max-requests: 600000
      ip-registry-cleaner:
        interval-ms: 3600000 
    captcha:
      anon-rate-limit:
        max-requests: 20
        time-window-ms: 3600000
      default-user-limit:
        hourly-max-requests: 1000
        daily-max-requests: 10000
      expiration-ms: 300000 # 5 minutes
      max-attempts: 3
    cvt-token:
      secret: ${CVT_TOKEN_SECRET}
      expiration-ms: 600000 # 10 minutes
    hmac-hash-service:
      secret: ${API_KEY_GENERATOR_SECRET}
    superuser:
      username: ${SUPERUSER_USERNAME}
      password: ${SUPERUSER_PASSWORD}

app:
  domain: https://cvtcaptcha.example.com
  captcha-dir: storage
  image:
    width: 400
    height: 300
    emote-r: 36

logging:
  pattern:
    file: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"